[versions]
android-compileSdk = "36"
android-minSdk = "21"
compose = "1.10.3"
compose-material3 = "1.9.0"
lifecycle = "2.10.0"
publish-plugin = "0.37.0"
poko = "0.23.1"

[libraries]
publish-gradlePlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish-plugin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

[plugins]
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
