import com.redmadrobot.konfeature.build.CheckAbiDumpTask
import com.redmadrobot.konfeature.build.DumpJvmAbiTask
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import org.jetbrains.kotlin.gradle.plugin.getKotlinPluginVersion

// ABI validation for the Android target of a KMP library module, alongside KGP's `abiValidation()`.
//
// KGP only dumps `KotlinAndroidTarget`s, and the target of the AGP KMP plugin is not one, so the
// Android surface has no dump of its own. This plugin adds `api/android/<module>.api`, checked by
// `check` and regenerated by `updateKotlinAbi` / `updateLegacyAbi` like the other dumps.

val androidAbiTools = configurations.register("androidAbiToolsClasspath") {
    isCanBeConsumed = false
    description = "Build Tools API implementation used to dump the Android ABI"
}
dependencies {
    // Must match the Kotlin Gradle plugin: the dump format is defined by the compiler version.
    androidAbiTools("org.jetbrains.kotlin:kotlin-build-tools-impl:${getKotlinPluginVersion()}")
}

// Applied after the Kotlin Multiplatform plugin; the `android` target itself is looked up lazily, as it
// only exists once the module's `kotlin { android { } }` block has run.
val kotlinExtension = the<KotlinMultiplatformExtension>()

val dumpFileName = "${project.name}.api"
val referenceDump = layout.projectDirectory.file("api/android/$dumpFileName")

val dumpAndroidAbi = tasks.register<DumpJvmAbiTask>("dumpAndroidAbi") {
    description = "Dumps the public ABI of the Android target into the build directory"
    val android = kotlinExtension.targets.getByName("android")
    classfiles.from(android.compilations.getByName("main").output.classesDirs)
    buildToolsClasspath.from(androidAbiTools)
    dumpFile.set(layout.buildDirectory.file("kotlin/abi-android/$dumpFileName"))
}

val updateAndroidAbi = tasks.register<Copy>("updateAndroidAbi") {
    group = "verification"
    description = "Writes the public ABI of the Android target to the reference dump file"
    from(dumpAndroidAbi.flatMap { it.dumpFile })
    into(referenceDump.asFile.parentFile)
}

val checkAndroidAbi = tasks.register<CheckAbiDumpTask>("checkAndroidAbi") {
    group = "verification"
    description = "Checks that the public ABI of the Android target matches the reference dump file"
    actualDump.set(dumpAndroidAbi.flatMap { it.dumpFile })
    referenceDumpPath.set(referenceDump.asFile.absolutePath)
    // A plain string on purpose: mapping the update task's provider would make this check depend on
    // the update task, i.e. overwrite the reference right before comparing against it.
    updateTaskPath.set("${project.path}:updateKotlinAbi")
}

tasks.matching { it.name == "updateKotlinAbi" || it.name == "updateLegacyAbi" }.configureEach {
    dependsOn(updateAndroidAbi)
}
tasks.named("check") {
    dependsOn(checkAndroidAbi)
}
